# Generated by Django 3.0.6 on 2020-07-10 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('thumbnail_1', models.ImageField(upload_to='items_pics/')),
                ('thumbnail_2', models.ImageField(upload_to='items_pics/')),
                ('thumbnail_3', models.ImageField(upload_to='items_pics/')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField()),
                ('show_to_friends', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(default='Fashion', related_name='posts', to='core.Category')),
            ],
        ),
    ]
